
export const EMOJIS = {
    
    BRAND: "🎮",
    LOGO: "🪙",
    GOLD: "💰",

    MEGASCALE: "🌟",
    CAPES: "🏹",
    BLOOD_TORVA: "🩸",
    RAIDS: "🐉",
    BOSSING: "⚔️",
    COMBAT: "⚡",
    ACCOUNTS: "🏃",
    QUESTS: "📜",
    MINIGAMES: "🎮",
    IRONMAN: "⛓️",
    SKILLS: "📊",

    CALCULATE: "🧮",
    ORDER: "📦",
    TICKET: "🎫",
    HELP: "❓",
    BACK: "⬅️",
    NEXT: "➡️",
    REFRESH: "🔄",
    CONFIRM: "✅",
    CANCEL: "❌",
    EDIT: "✏️",
    DELETE: "🗑️",
    SEARCH: "🔍",
    FILTER: "🔽",
    SORT: "📊",

    PENDING: "⏳",
    IN_PROGRESS: "🔄",
    COMPLETED: "✅",
    CANCELLED: "❌",
    ERROR: "❌",
    SUCCESS: "✅",
    WARNING: "⚠️",
    INFO: "ℹ️",

    CRYPTO: "💎",
    BITCOIN: "₿",
    ETHEREUM: "Ξ",
    PAYPAL: "💳",
    BANK: "🏦",
    CASH: "💵",

    PRICE: "💰",
    DISCOUNT: "🏷️",
    PERCENTAGE: "📊",
    FIXED: "🔒",
    PER_LEVEL: "📈",
    PER_KILL: "⚔️",
    PER_ITEM: "📦",
    PER_HOUR: "⏰",

    USER: "👤",
    CUSTOMER: "🛒",
    WORKER: "👷",
    ADMIN: "👑",
    SUPPORT: "🆘",

    SERVICE: "🛠️",
    ACCOUNT: "🔐",
    SECURITY: "🔒",
    NOTIFICATION: "🔔",
    MESSAGE: "💬",
    EMAIL: "📧",
    PHONE: "📞",

    HOME: "🏠",
    MENU: "📋",
    LIST: "📝",
    GRID: "⊞",
    DETAILS: "📄",
    SETTINGS: "⚙️",
    CONFIG: "🔧",

    FIRE: "🔥",
    STAR: "⭐",
    HEART: "❤️",
    THUMBS_UP: "👍",
    THUMBS_DOWN: "👎",
    PARTY: "🎉",
    GIFT: "🎁",
    TROPHY: "🏆",
    MEDAL: "🏅",
    CROWN: "👑",
    DIAMOND: "💎",
    GEM: "💎",
    COIN: "🪙",
    MONEY: "💸",
    CARD: "💳",
    RECEIPT: "🧾",
    PACKAGE: "📦",
    TRUCK: "🚚",
    SHIELD: "🛡️",
    LOCK: "🔒",
    KEY: "🔑",
    MAGIC: "✨",
    SPARKLES: "✨",
    ROCKET: "🚀",
    LIGHTNING: "⚡",
    FIREWORKS: "🎆",
    CONFETTI: "🎊",

    LOADING: "⏳",
    SPINNER: "🔄",
    HOURGLASS: "⏰",
    CLOCK: "🕐",

    UP: "⬆️",
    DOWN: "⬇️",
    LEFT: "⬅️",
    RIGHT: "➡️",
    UP_LEFT: "↖️",
    UP_RIGHT: "↗️",
    DOWN_LEFT: "↙️",
    DOWN_RIGHT: "↘️",

    ONE: "1️⃣",
    TWO: "2️⃣",
    THREE: "3️⃣",
    FOUR: "4️⃣",
    FIVE: "5️⃣",
    SIX: "6️⃣",
    SEVEN: "7️⃣",
    EIGHT: "8️⃣",
    NINE: "9️⃣",
    TEN: "🔟",

    CHECKBOX_EMPTY: "☐",
    CHECKBOX_CHECKED: "☑️",
    RADIO_EMPTY: "⚪",
    RADIO_CHECKED: "🔘",

    SUNNY: "☀️",
    CLOUDY: "☁️",
    RAINY: "🌧️",
    STORMY: "⛈️",
    SNOWY: "❄️",

    PIZZA: "🍕",
    BURGER: "🍔",
    COFFEE: "☕",
    TEA: "🍵",
    BEER: "🍺",
    WINE: "🍷",

    DOG: "🐕",
    CAT: "🐱",
    BIRD: "🐦",
    FISH: "🐟",
    BUG: "🐛",
    SPIDER: "🕷️",

    BOOK: "📚",
    COMPUTER: "💻",
    
    WATCH: "⌚",
    CAMERA: "📷",
    VIDEO: "📹",
    MUSIC: "🎵",
    GAME: "🎮",
    DICE: "🎲",
    CARDS: "🃏",
    PUZZLE: "🧩",
    TOY: "🧸",
    BALL: "⚽",
    RIBBON: "🎀",
    PRESENT: "🎁",
    BALLOON: "🎈",
    CANDLE: "🕯️",
    LIGHT_BULB: "💡",
    BATTERY: "🔋",
    PLUG: "🔌",
    SCISSORS: "✂️",
    HAMMER: "🔨",
    WRENCH: "🔧",
    NUT_BOLT: "🔩",
    GEAR: "⚙️",
    LINK: "🔗",
    CHAIN: "⛓️",
    HOOK: "🪝",
    KNOT: "🪢",
    SAFETY_PIN: "🧷",
    PAPERCLIP: "📎",
    STAPLER: "📌",
    PUSHPIN: "📌",
    ROUND_PUSHPIN: "📍",
    PEN: "🖊️",
    PENCIL: "✏️",
    PAINTBRUSH: "🖌️",
    CRAYON: "🖍️",
    MEMO: "📝",
    BRIEFCASE: "💼",
    FILE_FOLDER: "📁",
    OPEN_FILE_FOLDER: "📂",
    CARD_INDEX: "📇",
    DIVIDERS: "🗂️",
    NEWSPAPER: "📰",
    NEWSPAPER_ROLL: "🗞️",
    BOOKMARK_TABS: "📑",
    BOOKMARK: "🔖",
    LABEL: "🏷️",
    MONEY_BAG: "💰",
    
    YEN: "💴",
    DOLLAR: "💵",
    EURO: "💶",
    POUND: "💷",
    MONEY_WITH_WINGS: "💸",
    CREDIT_CARD: "💳",
    
    CHART: "💹",
    ENVELOPE: "✉️",
    
    INCOMING_ENVELOPE: "📨",
    ENVELOPE_WITH_ARROW: "📩",
    OUTBOX_TRAY: "📤",
    INBOX_TRAY: "📥",
    
    CLOSED_MAILBOX: "📫",
    OPEN_MAILBOX: "📪",
    MAILBOX_WITH_MAIL: "📬",
    MAILBOX_WITH_NO_MAIL: "📭",
    POSTBOX: "📮",
    BALLOT_BOX: "🗳️",
    PENCIL2: "✏️",
    BLACK_NIB: "✒️",
    LOWER_LEFT_FOUNTAIN_PEN: "🖋️",
    LOWER_LEFT_BALLPOINT_PEN: "🖊️",
    LOWER_LEFT_PAINTBRUSH: "🖌️",
    LOWER_LEFT_CRAYON: "🖍️",
} as const;
