export const DISCORD_LIMITS = {
    SELECT_OPTIONS: 25,
    ACTION_ROWS: 5,
    OPTION_LABEL: 100,
    OPTION_DESCRIPTION: 100,
    PLACEHOLDER: 150,
    EMBED_TITLE: 256,
    EMBED_DESCRIPTION: 4096,
    EMBED_FIELD_VALUE: 1024,
    EMBED_FOOTER: 2048,
    MODAL_INPUTS: 5,
} as const;

export const MAX_SERVICES_PER_CATEGORY = DISCORD_LIMITS.SELECT_OPTIONS;

export const MAX_LISTED_BEFORE_OVERFLOW = DISCORD_LIMITS.SELECT_OPTIONS - 1;
